# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    # Runs a basic linter over Python, JSON, etc.
    # Configuration: https://github.com/marketplace/actions/super-linter
    - name: Super-Linter
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: false # Validate only changed files. (TODO: Remove after remediations.)

        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # exclude auto-generated question.html files in the examples directory
        # to suppress errors about pl-markdown body characters.
        FILTER_REGEX_EXCLUDE: '.*questions\/pl-faded-parsons-examples\/.*\/.*question.html'

    - name: Validate-Info-JSONs
      run: bash validation_workflow/validate_changed_files
